## CIND830 - Python Programming for Data Science  
### Assignment 2 (10% of the final grade)
### Due on March 15, 2021 11:59 PM

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF.
Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Juputer Notebook.

Use the JupyterHub server on the Google Cloud Platform, provided by your designated instructor, for this assignment. Ensure using Python 3.7.6 release then complete the assignment by inserting your Python code wherever seeing the string "#INSERT YOUR ANSWER HERE."

When you click the `File` button, from the top navigation bar, then select `Export Notebook As ...`,
a document (PDF or HTML format) will be generated that includes
 both the assignment content and the output of any embedded Python code chunks.

Using [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines,
submit **both** the IPYNB and the exported file (PDF or HTML).
Failing to submit both files will be subject to mark deduction.

*****

### Question 1 **[50 pts]**:

**a)** **[15 pts]** Define a function called `isSymmetrical` that takes a string value as a parameter and returns `TRUE` if the given string is Symmetrical. A string is said to be symmetrical if the reverse of the string is the same as string. For example, “madam” is symmetrical, but “water” is not symmetrical.

In [23]:
def isSymmetrical(s):
     
    mid = (len(s)-1)//2
    start = 0
    last = len(s)-1
    flag = 0
  
    # finds the middle of the string 
    while(start<mid): 
   
        # comparing letters from right 
        # from the letters from left 
        if (s[start]== s[last]): 
              
            start += 1
            last -= 1
        else: 
            flag = 1
            break
    
       
    # flag variable checks the symmetry  
    if flag == 0: 
        print("The entered string is symmetrical") 
    else: 
        print("The entered string is not symmetrical") 
          

In [24]:
isSymmetrical('madam')

The entered string is symmetrical


In [25]:
isSymmetrical('water')

The entered string is not symmetrical


**b)** **[5 pts]** Modify the `isSymmetrical` function you created in Q1.a to take any type of data as an input and return `TRUE` if the input is symmetrical. For example, "12321" is symmetrical, but "12345" is not symmetrical.

In [26]:
def isSymmetrical(s):
    
    if type(s) == int:
        s=str(s)
        n=len(s)
    elif type(s) == str:
        n = len(s)
    
     
    mid = (len(s)-1)//2
    start = 0
    last = len(s)-1
    flag = 0
  
     
    while(start<mid): 
   
         
        if (s[start]== s[last]): 
              
            start += 1
            last -= 1
        else: 
            flag = 1
            break
       
     
    if flag == 0: 
        return("The entered string is symmetrical") 
    else: 
        return("The entered string is not symmetrical") 
          

In [27]:
isSymmetrical('12321')

'The entered string is symmetrical'

**c)** **[10 pts]** Define a function called `isSymmetricalVec` that calls `isSymmetrical` function you updated in Q1.b to take a list of elements and return their results in a list.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns \[`TRUE`, `FALSE`, `TRUE`, `TRUE`, `FALSE`\]

In [28]:
def isSymmetricalVec(s):
    vec=[]
    for i in s:
        mid = (len(i)-1)//2
        start = 0
        last = len(i)-1
        flag = 0
  
    
        while(start<mid): 

             
            if (i[start]== i[last]): 

                start += 1
                last -= 1
            else: 
                flag = 1
                break

        
        if flag == 0: 
            vec.append('TRUE') 
        else: 
            vec.append('FALSE') 

    return(vec)      


In [29]:
isSymmetricalVec(["1441", "Apple", "radar", "232", "plane"])

['TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE']

**d)** **[10 pts]** Define a function called `isSymmetricalDict` by modifying the function you created in Q1.c to return the results in a dictionary with their corresponding input elements. \
For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns {"1441": `TRUE`, "Apple": `FALSE`, "radar": `TRUE`, "232": `TRUE`, "plane": `FALSE`\}

In [30]:
def isSymmetricalDict(s):
    thisdict={}
    for u in s:
        thisdict[u]=""
    
    for i in thisdict.keys():
        mid = (len(i)-1)//2
        start = 0
        last = len(i)-1
        flag = 0
  
    
        while(start<mid): 

            
            if (i[start]== i[last]): 

                start += 1
                last -= 1
            else: 
                flag = 1
                break

        
        if flag == 0: 
            thisdict[i]='TRUE'
        else: 
            thisdict[i]='FALSE'

    return(thisdict)      

    


In [31]:
isSymmetricalDict(["1441", "Apple", "radar", "232", "plane"])

{'1441': 'TRUE',
 'Apple': 'FALSE',
 'radar': 'TRUE',
 '232': 'TRUE',
 'plane': 'FALSE'}

**e)** **[10 pts]** Define a function called `isSymmetricalTuple` by modifying the function you created in Q1.d to traverse the values of the returned dictionary **in reverse order** and return the dictionary keys that has a **`TRUE`** value as a tuple.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns ("232", "radar","1441").

In [32]:
def isSymmetricalTuple(s):
    thisdict={}
    for u in s:
        thisdict[u]=""
    
    for i in thisdict.keys():
        mid = (len(i)-1)//2
        start = 0
        last = len(i)-1
        flag = 0
  
   
        while(start<mid): 

            
            if (i[start]== i[last]): 

                start += 1
                last -= 1
            else: 
                flag = 1
                break

         
        if flag == 0: 
            thisdict[i]='TRUE'
        else: 
            thisdict[i]='FALSE'
    
    values=[]
    for key,value in thisdict.items():
        if value =='TRUE':
            values.append(key)
    
    values.reverse()
    values= tuple(values)
    
    return(values)      

    


In [33]:
isSymmetricalTuple(["1441", "Apple", "radar", "232", "plane"])

('232', 'radar', '1441')

*****



### Question 2 **[80 pts]** :



**a)** **[15 pts]** Define a function called `minSubStr` that takes two string arguments ( S and T ), and returns `TRUE` if the characters of *T* exist in *S*, else returns `FALSE`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns `TRUE` (`T = "ABCD"`, returns `FALSE)`


In [39]:
S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'
T = 'ABC'

In [35]:
def minSubStr(S,T):

    v=[]
    for i in S:
        v.append(i)
    total = 0 
    for element in T:
        if element in v:
            total = total+1

    if total == len(T):
        print(True)
    else:
        print(False)
        

     

In [36]:
minSubStr(S,T)

True


In [37]:
T = "ABCD"

In [38]:
minSubStr(S,T)

False


**b)** **[15 pts]** Modify your `minSubStr` function defined in Q2.a to return the first possible substring (traversing from left) containing all the elements of `T`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"BxxAxxC"`**

In [40]:
def minSubStr(S,T):
    total = 0
    v=[]
    sub=[]
    for i in S:
        v.append(i)

    while total < len(T): 
        for element in v:
            if element in T:
                total=total+1
                sub.append(element)
            elif total == len(T):
                break
            elif total>=1:
                sub.append(element)
    if total == len(T):
        return(''.join(sub))
    elif total<len(T):
        return("The values in T are not all in the values in S")
    

In [41]:
minSubStr(S,T)  

'BxxAxxC'

**c)** **[20 pts]** Modify your `minSubStr` function defined in Q2.b to return the shortest substring containing all the elements of T. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxCxB"`**


In [62]:
def minSubStr(S, T):
    htable={}
    for i in T:
        if i not in htable:
            htable[i]=1
        else: htable[i]+=1
    Total=len(T)
    start=0; minSize=10000; minStart=0
    for end in range(len(S)):
        if S[end] in htable:
            htable[S[end]]-=1
            if htable[S[end]]>=0:
                Total-=1
        if Total==0:
            while True:
                if S[start] in htable:
                    if htable[S[start]]<0:
                        htable[S[start]]+=1
                    else:
                        break
                start+=1
            if minSize>end-start+1:
                minSize=end-start+1; minStart=start
    if minSize==10000: return ''
    else: return S[minStart:minStart+minSize]

In [63]:
minSubStr(S,T)

'AxCxB'

**d)** **[30 pts]** modify your `minSubStr` function defined in Q2.c to return the shortest substring containing all the elements of T in order. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxxBxC"`**

In [65]:
#couldn't figure it out in time
def minSubStr(S, T):
    htable={}
    for i in T:
        if i not in htable:
            htable[i]=1
        else: htable[i]+=1
    Total=len(T)
    start=0; minSize=10000; minStart=0
    for end in range(len(S)):
        if S[end] in htable:
            htable[S[end]]-=1
            if htable[S[end]]>=0:
                Total-=1
        if Total==0:
            while True:
                if S[start] in htable:
                    if htable[S[start]]<0:
                        htable[S[start]]+=1
                    else:
                        break
                start+=1
            if minSize>end-start+1:
                minSize=end-start+1; minStart=start
    if minSize==10000: return ''
    else: return S[minStart:minStart+minSize]

In [66]:
minSubStr(S,T)

'AxCxB'

*****

### Question 3 **[30 pts]**:


**a)** Complete the given code to define three classes, Shape, Oval and Circle. 
- Shape will be the parent class of Oval and Circle. 
- Randomly create ten objects from Oval and Circle classes using the ``for`` loop given below
- Your code should produce correct number of Shapes, Circle and Oval objects. The count of objects should be calculated within the class definitions. 
  - Example output (note that since it is random every time it will be a different number of shapes) \\
  There are  10 random shape objects ['Circle', 'Circle', 'Circle', 'Circle', 'Oval', 'Circle', 'Oval', 'Oval', 'Circle', 'Circle'] \\
	 3 of them are ovals \\
	 7 of them are cirlces \\


In [11]:
#excecute this code block second. And then execute the rest normally
class shape:
    """the shape class is used to define the counters for the other classes"""
    count=0
    ovalcounter=0
    circlecounter=0

    def countShape(self):
        for i in self:
            if i == "Oval":
                shape.ovalcounter+=1
                shape.count+=1
            elif i == "Circle":
                shape.circlecounter+=1
                shape.count+=1
        return shape.count
            
class oval(shape):
    """the oval class inherits the shape class and returns its oval counter"""
    def countOval(self):
        return shape.ovalcounter
        
class circle(shape):
    """the circle class inherits the shape class and returns the circle counter"""
    def countCircle(self):
        return shape.circlecounter

In [10]:
"""execute this code block first"""
objs=[]

from random import choice
list_of_shapes = [choice(['Circle', 'Oval']) for x in range(10)]
for shape in list_of_shapes:
  if shape == 'Oval':
    objs.append(shape)
  else:
    objs.append(shape)

In [12]:
a=shape.countShape(objs)    
o=oval.countOval(objs)
c=circle.countCircle(objs)

In [13]:
print("there are "+str(a)+" random shape objects")
print(list_of_shapes)
print(str(o)+" of them are ovals")
print(str(c) + " of them are circles")

there are 10 random shape objects
['Circle', 'Circle', 'Oval', 'Circle', 'Circle', 'Circle', 'Oval', 'Circle', 'Circle', 'Circle']
2 of them are ovals
8 of them are circles


#### This is the end of assignment 2